# Generated by Django 5.0.4 on 2024-05-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=255)),
                ('BirthYear', models.CharField(max_length=255)),
                ('Age', models.CharField(max_length=255)),
                ('Gender', models.CharField(max_length=255)),
                ('Profession', models.CharField(max_length=255)),
            ],
        ),
    ]
