# Generated by Django 5.0.4 on 2024-05-05 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fin_tech', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='Age',
            field=models.CharField(db_column='Age', max_length=255),
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='Age',
            new_name='age',
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='BirthYear',
            field=models.CharField(db_column='BirthYear', max_length=255),
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='BirthYear',
            new_name='birthyear',
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Gender',
            field=models.CharField(db_column='Gender', max_length=255),
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='Gender',
            new_name='gender',
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Name',
            field=models.CharField(db_column='Name', max_length=255),
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='Name',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='Profession',
            field=models.CharField(db_column='Profession', max_length=255),
        ),
        migrations.RenameField(
            model_name='personaldetails',
            old_name='Profession',
            new_name='profession',
        ),
    ]
